defaults:
  - algo: apg
  - env: pc
  - dynamics: pointmass # [pointmass, quadrotor]
  - network: mlp # [mlp, cnn]
  - sensor: camera # [camera, lidar, relpos]
  - _self_
  # - override hydra/launcher: joblib

n_envs: 4096
l_rollout: ${algo.l_rollout}
n_updates: 1000
device: 0
headless: True

runname: ""
checkpoint: # must be an absolute path. example: "/home/username/workspace/quaddif/outputs/2024-12-12/09-00-00"

seed: -1
torch_deterministic: False

hydra:
  sweep:
    dir: ./outputs/${now:%Y-%m-%d}/multirun/${now:%H-%M-%S}
  # launcher:
    # n_jobs: 8