defaults:
  - algo: apg_sto
  - env: pc
  - dynamics: pointmass # [pointmass, quadrotor]
  - network: mlp # [mlp, cnn]
  - sensor: camera # [camera, lidar, relpos]
  - _self_
  - override hydra/launcher: joblib

n_envs: 4096
l_rollout: ${algo.l_rollout}
n_updates: 1000
device: 0
n_jobs: 2
headless: True
record_video: False
video_saveas: mp4 # [mp4, tensorboard]

runname: ""
checkpoint: # must be an absolute path. example: "/home/username/workspace/quaddif/outputs/2024-12-12/09-00-00"
export: False

seed: -1
torch_deterministic: False

env:
  dt: 0.0333

hydra:
  sweep:
    dir: ./outputs/${now:%Y-%m-%d}/multirun/${now:%H-%M-%S}
  launcher:
    n_jobs: ${n_jobs}