defaults:
  - algo: apg
  - env: position_control
  - dynamics: pointmass
  - _self_
  # - override hydra/launcher: joblib

n_envs: 4096
l_rollout: ${algo.l_rollout}
n_updates: 1000
device: 0

headless: True

seed: -1
torch_deterministic: False
hydra:
  sweep:
    dir: ./outputs/${now:%Y-%m-%d}/multirun/${now:%H-%M-%S}
  # launcher:
    # n_jobs: 8