defaults:
  - algo: apg_sto
  - env: pc
  - dynamics: pointmass_c # [pointmass, quadrotor]
  - network: mlp # [mlp, cnn]
  - sensor: camera # [camera, lidar, relpos]
  - _self_
  - override hydra/help: test_help
  - override hydra/launcher: joblib
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  # - override hydra/sweeper: optuna_sweep

l_rollout: ${algo.l_rollout}
n_agents: 1
n_envs: 4096
n_steps: 10000
device: 0
n_jobs: 1
max_vel: 5.0

headless: True
display_image: False
record_video: False
video_saveas: mp4 # [mp4, tensorboard]
use_training_cfg: False

runname: ""
checkpoint: # must be an absolute path. example: "/home/username/workspace/quaddif/outputs/2024-12-12/09-00-00"
export: False

seed: 0
torch_deterministic: False

env:
  dt: 0.0333
  min_target_vel: ${max_vel}
  max_target_vel: ${max_vel}

hydra:
  sweep:
    dir: ./outputs/${now:%Y-%m-%d}/multirun/${now:%H-%M-%S}
  launcher:
    n_jobs: ${n_jobs}