defaults:
  - algo: apg_sto
  - env: pc
  - dynamics: pmc # [pmc, pmd, quad]
  - network: mlp # [mlp, cnn]
  - sensor: camera # [camera, lidar, relpos]
  - logger: tensorboard # [tensorboard, wandb]
  - _self_
  - override hydra/help: train_help
  - override hydra/launcher: joblib
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  # - override hydra/sweeper: optuna_sweep

# use rollout length specified by specific algorithm
# since different algorithm need different rollout length to perform well
l_rollout: ${algo.l_rollout}
n_agents: 1
n_envs: 1024
n_updates: 1000
log_freq: 10
log_level: info
save_freq: 100
device: 0
n_jobs: 1
extern_path: /home/zxh/ws/wrqws/diff/traj/all_trajs.npz

headless: True
display_image: False
record_video: False

runname: "gazebofinetune"
checkpoint:
export:
  obs_frame: ${env.obs_frame}
  action_frame: ${dynamics.action_frame}
  jit: True
  onnx: True

torch_profile: False

seed: 0
torch_deterministic: False

env:
  dt: 0.0333

ref_path:

hydra:
  run:
    dir: ./outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/train/${now:%Y-%m-%d}/multirun/${now:%H-%M-%S}
  launcher:
    n_jobs: ${n_jobs}