defaults:
  - algo: track
  - env: pc
  - dynamics: pointmass_c # [pointmass_c, pointmass_d, quadrotor]
  - network: mlp # [mlp, cnn]
  - sensor: camera # [camera, lidar, relpos]
  - logger: tensorboard # [tensorboard, wandb]
  - _self_
  - override hydra/help: train_help
  - override hydra/launcher: joblib
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

ref_path: /home/zxh/ws/wrqws/fast_fly_ws/src/Fast-fly/script/fast_fly/data
n_agents: 1
n_envs: 32
