from setuptools import setup, find_packages

setup(
    name='diffaero',
    version='1.0',
    # packages=find_packages(),
    packages=[".", "env", "algo", "network", "utils", "script"],
    install_requires=[
        'torch>=2.0.0',
        'tensordict',
        'taichi',
        'tqdm',
        'hydra-core',
        'hydra-joblib-launcher',
        'hydra_colorlog',
        'hydra-optuna-sweeper',
        'welford_torch',
        'line_profiler',
        'tensorboard',
        'tensorboardX',
        'torch-tb-profiler',
        'wandb',
        'gpustat',
        'opencv-python',
        'pytorch3d@git+https://github.com/facebookresearch/pytorch3d.git@stable#egg=pytorch3d',
        'open3d',
        'numpy',
        'moviepy',
        'imageio',
        'imageio-ffmpeg',
        'matplotlib',
        'onnx',
    ],
    author='Xinhong Zhang',
    author_email='zxh0916@126.com',
    description='',
    url='https://github.com/zxh0916/diffaero'
)
