// Generated by gencpp from file accel_control/DepthImage.msg
// DO NOT EDIT!


#ifndef ACCEL_CONTROL_MESSAGE_DEPTHIMAGE_H
#define ACCEL_CONTROL_MESSAGE_DEPTHIMAGE_H

#include <ros/service_traits.h>


#include <accel_control/DepthImageRequest.h>
#include <accel_control/DepthImageResponse.h>


namespace accel_control
{

struct DepthImage
{

typedef DepthImageRequest Request;
typedef DepthImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DepthImage
} // namespace accel_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::accel_control::DepthImage > {
  static const char* value()
  {
    return "c62de067401b31d4e5f3582933f57d5b";
  }

  static const char* value(const ::accel_control::DepthImage&) { return value(); }
};

template<>
struct DataType< ::accel_control::DepthImage > {
  static const char* value()
  {
    return "accel_control/DepthImage";
  }

  static const char* value(const ::accel_control::DepthImage&) { return value(); }
};


// service_traits::MD5Sum< ::accel_control::DepthImageRequest> should match
// service_traits::MD5Sum< ::accel_control::DepthImage >
template<>
struct MD5Sum< ::accel_control::DepthImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::accel_control::DepthImage >::value();
  }
  static const char* value(const ::accel_control::DepthImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::accel_control::DepthImageRequest> should match
// service_traits::DataType< ::accel_control::DepthImage >
template<>
struct DataType< ::accel_control::DepthImageRequest>
{
  static const char* value()
  {
    return DataType< ::accel_control::DepthImage >::value();
  }
  static const char* value(const ::accel_control::DepthImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::accel_control::DepthImageResponse> should match
// service_traits::MD5Sum< ::accel_control::DepthImage >
template<>
struct MD5Sum< ::accel_control::DepthImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::accel_control::DepthImage >::value();
  }
  static const char* value(const ::accel_control::DepthImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::accel_control::DepthImageResponse> should match
// service_traits::DataType< ::accel_control::DepthImage >
template<>
struct DataType< ::accel_control::DepthImageResponse>
{
  static const char* value()
  {
    return DataType< ::accel_control::DepthImage >::value();
  }
  static const char* value(const ::accel_control::DepthImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACCEL_CONTROL_MESSAGE_DEPTHIMAGE_H
