name: obstacle_avoidance

sensor: ${sensor}
dynamics: ${dynamics}
dt: 0.0333
length:
  default: 25
  enabled: False
  min: 25
  max: 25
height_scale: 0.25
n_envs: ${n_envs}
n_agents: ${n_agents}
max_time: 30
wait_before_truncate: 5.
max_target_vel: 6.
min_target_vel: 3.
last_action_in_obs: False
r_drone: 0.2
n_obstacles: 30
ground_plane: True

loss_weights:
  pointmass:
    vel: 0.5
    oa: 4.
    jerk: 0.005
    pos: 5.
    collision: 0.
  quadrotor:
    vel: 1.
    oa: 1.
    jerk: 1.
    pos: 5.
    collision: 0.

reward_weights:
  # for Reinforcement Learning
  # constant: 1.
  # pointmass:
  #   vel: 0.06
  #   oa: 0.6
  #   jerk: 0.0005
  #   pos: 0.5
  #   arrive: 0.
  #   collision: 5.

  # for SHA2C
  constant: 1.
  pointmass:
    vel: 0.06
    oa: 0.6
    jerk: 0.0005
    pos: 0.5
    arrive: 0.
    collision: 5.
  quadrotor:
    vel: 1.
    oa: 1.
    jerk: 1.
    pos: 5.
    collision: 50.

defaults:
  - render: oa_render
  - randomizer: default_randomizer
  - obstacles: outdoor
  - _self_
