name: obstacle_avoidance

sensor: ${sensor}
dynamics: ${dynamics}
dt: 0.0333
length: 25
height_scale: 0.25
n_envs: ${n_envs}
n_agents: ${n_agents}
max_time: 30
wait_before_truncate: 5.
max_target_vel: 8.
min_target_vel: 5.
r_drone: 0.2
n_obstacles: 50
ground_plane: True

n_substeps: 1

obstacles:
  n_obstacles: ${env.n_obstacles}
  sphere_percentage: 0.5
  sphere_radius_range: [0.6, 4.0, 0.4] # [min, max, step]
  cube_lwh_range: [0.6, 5.0, 0.4] # [min, max, step]
  randpos_std_min: 6
  randpos_std_max: 7

defaults:
  - render: oa_render
  - _self_
