name: obstacle_avoidance

sensor: ${sensor}
dynamics: ${dynamics}
dt: 0.0333
length: 7.5
n_envs: ${n_envs}
max_time: 30
max_vel: 3.
r_drone: 0.2
n_obstacles: 15
ground_plane: True

n_substeps: 1

obstacles:
  n_obstacles: ${env.n_obstacles}
  sphere_percentage: 0.5
  sphere_radius_range: [0.2, 2.0, 0.2] # [min, max, step]
  cube_lwh_range: [0.4, 2.0, 0.2] # [min, max, step]
  randpos_std_min: 1.
  randpos_std_max: 1.

defaults:
  - render: oa_render
  - _self_