name: obstacle_avoidance_grid

sensor: ${sensor}
dynamics: ${dynamics}
dt: 0.0333
length:
  default: 5
  enabled: True
  min: 3
  max: 7
height_scale: 0.25
n_envs: ${n_envs}
n_agents: ${n_agents}
obs_frame: "local" # "world" or "local"
max_time: 30
wait_before_truncate: 5.
max_target_vel: 5.
min_target_vel: 2.
last_action_in_obs: False
r_drone: 0.2
n_obstacles: 30
ground_plane: True

loss_weights:
  pointmass:
    vel: 1.
    vel_zdiff_factor: 3.
    oa: 2.
    jerk: 0.005
    pos: 5.
    collision: 10.
  quadrotor:
    vel: 1.
    oa: 1.
    jerk: 1.
    pos: 5.
    collision: 10.

reward_weights:
  constant: 4.
  pointmass:
    vel: 1.
    oa: 2.
    jerk: 0.005
    pos: 5.
    arrive: 0.
    collision: 10.
  quadrotor:
    vel: 1.
    oa: 1.
    jerk: 1.
    pos: 5.
    collision: 10.

grid:
  x_min: -2.
  x_max:  2.
  y_min: -2.
  y_max:  2.
  z_min: -1.
  z_max:  1.
  n_points: [20, 20, 10]

defaults:
  - render: oa_render
  - randomizer: default_randomizer
  - imu: default_imu
  - obstacles: small_room
  - _self_
