name: obstacle_avoidance_grid

sensor: ${sensor}
dynamics: ${dynamics}
dt: 0.0333
length: 15
height_scale: 0.25
n_envs: ${n_envs}
max_time: 30
max_vel: 5.
r_drone: 0.2
n_obstacles: 30
ground_plane: True

n_substeps: 1

grid:
  x_min: -2.
  x_max: 2.
  y_min: -2.
  y_max: 2.
  z_min: -1.
  z_max: 1.
  n_points: [20, 20, 10]

obstacles:
  n_obstacles: ${env.n_obstacles}
  sphere_percentage: 0.5
  sphere_radius_range: [0.6, 2.0, 0.2] # [min, max, step]
  cube_lwh_range: [0.6, 3.0, 0.4] # [min, max, step]
  randpos_std_min: 2
  randpos_std_max: 3

defaults:
  - render: oa_render
  - _self_
