name: obstacle_avoidance_grid

sensor: ${sensor}
dynamics: ${dynamics}
dt: 0.0333
length: 5
height_scale: 0.25
n_envs: ${n_envs}
n_agents: ${n_agents}
max_time: 30
wait_before_truncate: 5.
max_target_vel: 5.
min_target_vel: 2.
last_action_in_obs: False
r_drone: 0.2
n_obstacles: 30
ground_plane: True

n_substeps: 1

obstacles:
  walls: True
  ceiling: True
  n_obstacles: ${env.n_obstacles}
  height_scale: ${env.height_scale}
  sphere_percentage: 0.5
  sphere_radius_range: [0.1, 0.5, 0.1] # [min, max, step]
  cube_lwh_range: [0.1, 1.0, 0.1] # [min, max, step]
  randpos_std_min: 1
  randpos_std_max: 1.5
  safety_range: 1.0

loss:
  pointmass:
    vel: 1.
    oa: 2.
    jerk: 0.005
    pos: 5.
    collision: 10.
  quadrotor:
    vel: 1.
    oa: 1.
    jerk: 1.
    pos: 5.

grid:
  x_min: -2.
  x_max:  2.
  y_min: -2.
  y_max:  2.
  z_min: -1.
  z_max:  1.
  n_points: [20, 20, 10]

defaults:
  - render: oa_render
  - randomizer: default_randomizer
  - _self_
