name: obstacle_avoidance

sensor: ${sensor}
dynamics: ${dynamics}
dt: 0.0333
length: 5
height_scale: 0.25
n_envs: ${n_envs}
n_agents: ${n_agents}
max_time: 30
wait_before_truncate: 5.
max_target_vel: 5.
min_target_vel: 2.
last_action_in_obs: False
r_drone: 0.2
n_obstacles: 30
ground_plane: True

n_substeps: 1

obstacles:
  walls: True
  ceiling: True
  n_obstacles: ${env.n_obstacles}
  height_scale: ${env.height_scale}
  sphere_percentage: 0.5
  sphere_radius_range: [0.6, 2.0, 0.4] # [min, max, step]
  cube_lw_range: [0.1, 1.0, 0.1] # [min, max, step]
  cube_h_range: [3.0, 5.0, 1.0] # [min, max, step]
  randomize_cube_pose: True
  cube_roll_pitch_range: 15. # degrees
  randpos_std_min: 1
  randpos_std_max: 1.5
  safety_range: 1.0

loss_weights:
  pointmass:
    vel: 1.
    oa: 2.
    jerk: 0.005
    pos: 5.
    collision: 10.
  quadrotor:
    vel: 1.
    oa: 1.
    jerk: 1.
    pos: 5.

reward_weights:
  constant: 4.
  pointmass:
    vel: 1.
    oa: 2.
    jerk: 0.005
    pos: 5.
    collision: 10.
  quadrotor:
    vel: 1.
    oa: 1.
    jerk: 1.
    pos: 5.

defaults:
  - render: oa_render
  - randomizer: default_randomizer
  - _self_
