name: obstacle_avoidance_yopo

sensor: ${sensor}
dynamics: ${dynamics}
dt: 0.0333
length: 15
height_scale: 0.25
n_envs: ${n_envs}
n_agents: ${n_agents}
max_time: 30
wait_before_truncate: 5.
max_target_vel: 10.
min_target_vel: 5.
r_drone: 0.2
n_obstacles: 30
ground_plane: True

n_substeps: 1

obstacles:
  walls: False
  ceiling: False
  n_obstacles: ${env.n_obstacles}
  height_scale: ${env.height_scale}
  sphere_percentage: 0.5
  sphere_radius_range: [0.6, 2.0, 0.2] # [min, max, step]
  cube_lwh_range: [0.6, 3.0, 0.4] # [min, max, step]
  randpos_std_min: 2
  randpos_std_max: 3
  safety_range: 1.7

loss:
  pointmass:
    vel: 1.
    oa: 4.
    pos: 0.
    collision: 0.

defaults:
  - render: oa_render
  - _self_
