name: obstacle_avoidance_yopo

sensor: ${sensor}
dynamics: ${dynamics}
dt: 0.0333
length:
  default: 25
  enabled: False
  min: 25
  max: 25
height_scale: 0.25
n_envs: ${n_envs}
n_agents: ${n_agents}
obs_frame: "local" # "world" or "local"
max_time: 30
wait_before_truncate: 5.
max_target_vel: 10.
min_target_vel: 5.
r_drone: 0.2
n_obstacles: 30
ground_plane: True

loss_weights:
  pointmass:
    vel: 1.
    oa: 4.
    pos: 0.
    collision: 0.

defaults:
  - render: oa_render
  - randomizer: default_randomizer
  - obstacles: outdoor
  - _self_
