name: obstacle_avoidance_yopo

sensor: ${sensor}
dynamics: ${dynamics}
dt: 0.0333
length:
  default: 20
  enabled: True
  min: 10
  max: 30
height_scale: 0.25
n_envs: ${n_envs}
n_agents: ${n_agents}
obs_frame: "world" # "world" or "local"
max_time: 30
wait_before_truncate: 0.5
max_target_vel: 10.
min_target_vel: 5.
last_action_in_obs: ~
r_drone: 0.2
n_obstacles: 30
ground_plane: True

loss_weights:
  pointmass:
    vel: 1.
    z: 0.5
    oa: 4.
    pos: 2.
    collision: 20.

reward_weights: ~

enable_grid: False
defaults:
  - render: oa_render
  - randomizer: default_randomizer
  - imu: default_imu
  - obstacles: outdoor
  - grid: big
  - _self_
