name: grid_wm

# actor
network:
  name: mlp
  hidden_dim: [256, 128]

l_rollout: 32
buffer_size: 1e4
batch_size: 256

actor_lr: 1e-3
max_grad_norm: 1.
n_epochs: 4

entropy_weight: 0.03

encoder:
  img_encoder:
    image_shape: [1, 9, 16]
    channels: [16, 32]
    stride: 2
    kernel_size: 4
    act: SiLU
    norm: BatchNorm2d
  recon_image: False

  state_encoder:
    state_dim: 10
    embedding_dim: 64
    hidden_units: [64]
    act: SiLU
    norm: LayerNorm
  recon_state: True

rssm:
  action_dim: 3
  stoch: 32
  classes: 32
  deter: 256
  hidden: 256
  act: SiLU
  norm: LayerNorm

decoder:
  use_mlp: True
  cnndecoder:
    channels: [64, 32, 16, 3]
    stride: 2
    kernel_size: 4
    act: SiLU
    norm: BatchNorm2d

  mlpdecoder:
    hidden_units: [256, 256]
    act: SiLU
    norm: LayerNorm

train:
  lr: 3e-4
  grad_norm: 100.
  grid_pos_weight: 10

  # weight of loss funcs
  rec_img_weight: 1.
  rec_state_weight: 1.
  dyn_weight: 0.5
  rep_weight: 0.1
  rew_weight: 1.
  ter_weight: 1.
  grid_loss: 1.