name: grid
network: ${network}

# encoder
encoder_hidden_dim: [128]
encoder_rnn_n_layer: 1
encoder_rnn_hidden_dim: 256

latent_dim: 512
l_rollout: 32
buffer_size: 1e4
batch_size: 256

encdec_lr: 0.001
actor_lr: 0.001
max_grad_norm: 1.

entropy_weight: 0.03
grid_recon_weight: 1
image_recon_weight: 0

grid_pos_weight: 10