name: grid_wm

l_rollout: 32
gamma: 0.99
lmbda: 0.95
odom_free: False

agent:
  actor:
    name: mlp
    hidden_dim: [256, 128]
    lr: 0.003
    max_grad_norm: 1.
  critic:
    name: mlp
    hidden_dim: [256, 128]
    lr: 0.003
    max_grad_norm: 10.
    n_epochs: 8
  
  entropy_weight: 0.01

wm:
  compile: True
  l_rollout: ${algo.l_rollout}
  odom_free: ${algo.odom_free}
  encoder:
    image:
      # not used
      channels: [16, 32]
      stride: 2
      kernel_size: 4
      act: SiLU
      norm: BatchNorm2d

    state:
      embedding_dim: 64
      hidden_units: [64]
      act: SiLU
      norm: LayerNorm

  rssm:
    action_dim: 3
    stoch: 32
    classes: 32
    deter: 256
    hidden: 256
    act: SiLU
    norm: LayerNorm

  decoder:
    image:
      enable: False
      use_mlp: True
      cnndecoder:
        channels: [64, 32, 16, 3]
        stride: 2
        kernel_size: 4
        act: SiLU
        norm: BatchNorm2d

      mlpdecoder:
        hidden_units: [256, 256]
        act: SiLU
        norm: LayerNorm
    
    state:
      enable: True
    
    grid: 
      enable: True
      use_mlp: True
    
    reward:
      enable: False

  train:
    lr: 3e-4
    grad_norm: 10.
    grid_pos_weight: 10
    term_pos_weight: 100

    # weight of loss funcs
    rec_img_weight: 1.
    rec_state_weight: 1.
    free_bits: 1.
    dyn_weight: 0.01
    rep_weight: 0.002
    rew_weight: 1.
    ter_weight: 1.
    grid_weight: 1.
    soft_label: 0.

    batch_size: ${n_envs}
    buffer_size: 5e4
    n_epochs: 4