name: yopo

min_pitch: -60
max_pitch: 60
min_yaw: -75
max_yaw: 75
n_pitch: 3
n_yaw: 5
feature_dim: 16
tmax: 2
n_points_per_sec: 15
r: 2.5
r_range: 2.5
pitch_range: 15
yaw_range: 30
v_range: 2
a_range: 2

lr: 0.003
n_epochs: 1
expl_prob: 0.1